services:
  # Prometheus - 메트릭 수집
  prometheus:
    image: prom/prometheus:latest
    container_name: exchange-rate-user-prometheus-local
    ports:
      - "9091:9090"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./monitoring/prometheus-local.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_local:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - shared-network-local

  # Grafana - 대시보드
  grafana:
    image: grafana/grafana:latest
    container_name: exchange-rate-user-grafana-local
    ports:
      - "3001:3000"
    environment:
      - TZ=Asia/Seoul
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-user}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_USER_PASSWORD:-user123}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${GMAIL_USERNAME}
      - GF_SMTP_PASSWORD=${GMAIL_APP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GMAIL_USERNAME}
      - GF_SMTP_FROM_NAME=Grafana Alert (User App Local)
    volumes:
      - grafana_data_local:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - shared-network-local

  # Node Exporter - 시스템 메트릭
  node-exporter:
    image: prom/node-exporter:latest
    container_name: exchange-rate-user-node-exporter-local
    ports:
      - "9101:9100"  # Admin과 포트 충돌 방지
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - shared-network-local

volumes:
  prometheus_data_local:
  grafana_data_local:

networks:
  shared-network-local:
    name: user-network-local
    driver: bridge

