services:
  # User Application
  user-app:
    build: .
    container_name: exproject-user-app
    ports:
      - "8081:8081"
    environment:
      # Database
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # Redis (User App 전용)
      REDIS_HOST: user-redis
      REDIS_PORT: 6379
      
      # Application
      SPRING_PROFILES_ACTIVE: prod
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      
      # Email
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      
      # Exchange API
      EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}
      
      # OAuth2
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      
      # AWS S3 (선택사항)
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - user-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


volumes:
  uploads:
  logs:

networks:
  user-network:
    name: user-network
    driver: bridge

