spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 기본값: local
  
  # 데이터베이스 설정 (로컬 개발용)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:}
    password: ${GMAIL_APP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          debug: true
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - email
              - profile
        provider:
          google:
            user-name-attribute: email
  
  # Spring Boot 기본 에러 페이지 비활성화
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # 에러 페이지 완전 비활성화
  error:
    whitelabel:
      enabled: false

# 공통 설정 (모든 환경에서 공유)
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.domain

# 서버 설정 (로컬 개발용)
server:
  port: 8081

# Exchange API 설정
exchange:
  api-key: ${EXCHANGE_API_KEY:}