global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # 컨테이너 내부 포트

  # Node Exporter - 시스템 메트릭
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # 컨테이너 내부 포트

  # Spring Boot User App
  - job_name: 'user-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['exproject-user-app:8081']
    scrape_interval: 15s
    scrape_timeout: 10s

