global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # 컨테이너 내부 포트

  # Node Exporter - 시스템 메트릭
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # 컨테이너 내부 포트

  # Spring Boot User App (Production - 실제 호스트명 사용)
  - job_name: 'user-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['exproject-user-app:8081']  # Docker 컨테이너명 사용
    scrape_interval: 60s
    scrape_timeout: 30s
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'hikaricp_.*'
        target_label: 'component'
        replacement: 'database'

