{
 "title": "데이터베이스 모니터링",
 "tags": [ "database" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "데이터베이스 연결 풀",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active > 0",
     "legendFormat": "활성 연결 ({{pool}})"
    },
    { "expr": "hikaricp_connections_idle > 0", "legendFormat": "유휴 연결 ({{pool}})" }
   ]
  },
  {
   "title": "데이터베이스 연결 생성 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_max > 0",
     "legendFormat": "최대 생성 시간 ({{pool}})"
    },
    {
     "expr": "hikaricp_connections_creation_seconds_sum > 0",
     "legendFormat": "총 생성 시간 ({{pool}})"
    },
    {
     "expr": "hikaricp_connections_creation_seconds_count > 0",
     "legendFormat": "생성 횟수 ({{pool}})"
    }
   ]
  },
  {
   "title": "데이터베이스 연결 타임아웃",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total > 0",
     "legendFormat": "연결 타임아웃 ({{pool}})"
    }
   ]
  },
  {
   "title": "데이터베이스 연결 사용 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_max > 0",
     "legendFormat": "최대 사용 시간 ({{pool}})"
    },
    {
     "expr": "hikaricp_connections_usage_seconds_sum > 0",
     "legendFormat": "총 사용 시간 ({{pool}})"
    },
    {
     "expr": "hikaricp_connections_usage_seconds_count > 0",
     "legendFormat": "사용 횟수 ({{pool}})"
    }
   ]
  }
 ]
}